-- MySQL Script generated by MySQL Workbench
-- Fri Jun  5 22:51:39 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema miniblog
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `miniblog` ;

-- -----------------------------------------------------
-- Schema miniblog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `miniblog` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `miniblog` ;

-- -----------------------------------------------------
-- Table `miniblog`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `miniblog`.`categorias` ;

CREATE TABLE IF NOT EXISTS `miniblog`.`categorias` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(100) NOT NULL,
  `descripcion_categoria` TEXT NULL,
  `estado_categoria` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miniblog`.`entradas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `miniblog`.`entradas` ;

CREATE TABLE IF NOT EXISTS `miniblog`.`entradas` (
  `id_entrada` INT NOT NULL AUTO_INCREMENT,
  `titulo_entrada` VARCHAR(100) NOT NULL,
  `id_categoria` INT NULL,
  `fecha_publicacion` DATE NOT NULL,
  `resumen_entrada` VARCHAR(255) NULL,
  `cuerpo_entrada` LONGTEXT NULL,
  `estado_entrada` INT NOT NULL,
  `imagen_entrada` VARCHAR(255) NULL,
  PRIMARY KEY (`id_entrada`),
  INDEX `fk_id_categoria_idx` (`id_categoria` ASC),
  CONSTRAINT `fk_id_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `miniblog`.`categorias` (`id_categoria`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miniblog`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `miniblog`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `miniblog`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `correo_usuario` VARCHAR(100) NOT NULL,
  `nombre_usuario` VARCHAR(100) NOT NULL,
  `clave_acceso` TEXT NULL,
  `nivel_acceso` INT NOT NULL DEFAULT 0,
  `hash_recuperacion` VARCHAR(255) NULL,
  `estado_usuario` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`nombre_usuario` ASC),
  UNIQUE INDEX `correo_UNIQUE` (`correo_usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miniblog`.`generos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `miniblog`.`generos` ;

CREATE TABLE IF NOT EXISTS `miniblog`.`generos` (
  `id_genero` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_genero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miniblog`.`personas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `miniblog`.`personas` ;

CREATE TABLE IF NOT EXISTS `miniblog`.`personas` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NULL,
  `fecha_nacimiento` DATE NULL,
  `id_genero` INT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id_persona`),
  INDEX `fk_id_genero_idx` (`id_genero` ASC),
  INDEX `fk_id_persona_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_id_genero`
    FOREIGN KEY (`id_genero`)
    REFERENCES `miniblog`.`generos` (`id_genero`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `miniblog`.`usuarios` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miniblog`.`perfiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `miniblog`.`perfiles` ;

CREATE TABLE IF NOT EXISTS `miniblog`.`perfiles` (
  `id_perfil` INT NOT NULL AUTO_INCREMENT,
  `nombre_publico` VARCHAR(255) NULL,
  `ubicacion` VARCHAR(255) NULL,
  `biografia` TEXT NULL,
  PRIMARY KEY (`id_perfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miniblog`.`escritores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `miniblog`.`escritores` ;

CREATE TABLE IF NOT EXISTS `miniblog`.`escritores` (
  `id_escritor` INT NOT NULL AUTO_INCREMENT,
  `id_persona` INT NOT NULL,
  `id_perfil` INT NULL,
  PRIMARY KEY (`id_escritor`),
  INDEX `fk_id_persona_idx` (`id_persona` ASC),
  INDEX `fk_id_perfil_idx` (`id_perfil` ASC),
  CONSTRAINT `fk_id_persona`
    FOREIGN KEY (`id_persona`)
    REFERENCES `miniblog`.`personas` (`id_persona`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_id_perfil`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `miniblog`.`perfiles` (`id_perfil`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miniblog`.`escritores_entradas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `miniblog`.`escritores_entradas` ;

CREATE TABLE IF NOT EXISTS `miniblog`.`escritores_entradas` (
  `id_escritor_entrada` INT NOT NULL AUTO_INCREMENT,
  `id_escritor` INT NOT NULL,
  `id_entrada` INT NOT NULL,
  PRIMARY KEY (`id_escritor_entrada`),
  INDEX `fk_id_escritor_idx` (`id_escritor` ASC),
  INDEX `fk_id_entrada_idx` (`id_entrada` ASC),
  CONSTRAINT `fk_id_escritor`
    FOREIGN KEY (`id_escritor`)
    REFERENCES `miniblog`.`escritores` (`id_escritor`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_id_entrada`
    FOREIGN KEY (`id_entrada`)
    REFERENCES `miniblog`.`entradas` (`id_entrada`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `miniblog`.`comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `miniblog`.`comentarios` ;

CREATE TABLE IF NOT EXISTS `miniblog`.`comentarios` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `id_persona` INT NOT NULL,
  `id_entrada` INT NOT NULL,
  `detalle_comentario` TEXT NULL,
  `estado_comentario` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_comentario`),
  INDEX `fk_id_entrada_idx` (`id_entrada` ASC),
  INDEX `fk_id_persona_idx` (`id_persona` ASC),
  CONSTRAINT `fk_id_persona`
    FOREIGN KEY (`id_persona`)
    REFERENCES `miniblog`.`personas` (`id_persona`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_id_entrada`
    FOREIGN KEY (`id_entrada`)
    REFERENCES `miniblog`.`entradas` (`id_entrada`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;